[package]
name = "babylon"
version = "0.1.0"
authors = ["CryptArchy <codexarcanum@gmail.com>"]
publish = false

[dependencies]
version = "2.0"
log = "0.3"
log4rs = { version = "0.4", features = ["toml"] }
clap = "2.13"
data-encoding = "1.1"
error-type = "0.1"
rand = "0.3"
redux = "0.1"
